name: iPad Scraper

on:
  workflow_dispatch:  # Allows manual triggering from GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.9'  # Specify a version
      
      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests
      
      - name: Run scraper
        run: python ipad_scraper.py
        
      - name: Upload CSV results
        uses: actions/upload-artifact@v3  # This remains the same as v3 is still valid
        with:
          name: scraper-results
          path: output.csv  # Adjust path as necessary
